//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ESBServer.rc
//
#define IDC_MINIMIZE                    2
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_ESBSERVER_DIALOG            102
#define IDD_ESBSERVER_CONRTOL_PANEL     102
#define IDS_BROWSERS                    102
#define IDR_ESBSERVER_MANAGER           103
#define IDR_ESBSERVER                   104
#define IDR_ESBSERVERMANAGER            105
#define IDD_CTAGS_PROPERTIES_PANEL      106
#define IDC_OUTLANE_PANEL               106
#define IDC_CUSTOM_FILTER               107
#define IDR_MAINFRAME                   128
#define IDD_OUTLINE_BROWSER             133
#define IDD_EMPTY_DIALOG                133
#define IDI_CLASS                       135
#define IDI_STRUCT                      136
#define IDI_UNION                       137
#define IDI_ENUM                        138
#define IDI_TYPEDEF                     139
#define IDI_FUNCTION                    140
#define IDI_PRIVATE_FIELD               141
#define IDI_PROTECTED_FIELD             142
#define IDI_PUBLIC_FIELD                143
#define IDI_PUBLIC_METHOD               144
#define IDI_PROTECTED_METHOD            145
#define IDI_PRIVATE_METHOD              146
#define IDI_PRIVATE_FIELD_S             147
#define IDI_PRIVATE_FIELD_C             148
#define IDI_PRIVATE_FIELD_SC            149
#define IDI_PROTECTED_FIELD_SC          150
#define IDI_PROTECTED_FIELD_S           151
#define IDI_PROTECTED_FIELD_C           152
#define IDI_PUBLIC_FIELD_SC             153
#define IDI_PUBLIC_FIELD_S              154
#define IDI_PUBLIC_FIELD_C              155
#define IDI_CS                          156
#define IDI_ICON1                       157
#define IDI_PUBLIC_METHOD_S             158
#define IDB_METHOD                      158
#define IDI_PUBLIC_METHOD_C             159
#define IDB_FIELD                       159
#define IDI_PUBLIC_METHOD_VCO           160
#define IDB_CLASS                       160
#define IDI_PUBLIC_METHOD_ACO           161
#define IDB_PUBLIC                      161
#define IDI_PUBLIC_METHOD_VC            162
#define IDB_PROTECTED                   162
#define IDI_PUBLIC_METHOD_AC            163
#define IDB_PRIVATE                     163
#define IDI_PUBLIC_METHOD_A             164
#define IDB_STATIC                      164
#define IDI_PUBLIC_METHOD_AO            165
#define IDB_CONST                       165
#define IDI_PUBLIC_METHOD_V             166
#define IDB_ABSTRACT                    166
#define IDI_PUBLIC_METHOD_VO            167
#define IDB_VIRTUAL                     167
#define IDB_OVERWRITEN                  168
#define IDB_PRIVATE_FIELD               169
#define IDB_PROTECTED_FIELD             170
#define IDB_PUBLIC_FIELD                171
#define IDB_NAMESPACE                   172
#define IDB_STRUCT                      173
#define IDB_UNION                       174
#define IDB_ENUM                        175
#define IDB_FUNCTION                    176
#define IDB_TYPEDEF                     178
#define IDR_OUTLINE_BROWSER_POPUPMENU   179
#define IDB_OUTLINE                     181
#define IDB_NO_PUBLIC_A                 183
#define IDB_PUBLIC_ONLY_A               183
#define IDB_CLOSE_A                     184
#define IDB_NO_STATIC_A                 185
#define IDB_NO_FIELDS_A                 186
#define IDB_SORT_A                      187
#define IDI_OUTLINE                     188
#define IDB_CLOSE_F                     188
#define IDB_NO_FIELDS_F                 189
#define IDB_NO_PUBLIC_F                 190
#define IDB_PUBLIC_ONLY_F               190
#define IDD_ESBSERVER_OPTION_PANEL      190
#define IDB_NO_STATIC_F                 191
#define IDD_WORKSPACE_BROWSER           191
#define IDB_SORT_F                      192
#define IDB_NO_FIELDS_S                 193
#define IDB_NO_PUBLIC_S                 194
#define IDB_PUBLIC__ONLY_S              194
#define IDB_PUBLIC_ONLY_S               194
#define IDB_NO_STATIC_S                 195
#define IDB_SORT_S                      196
#define IDB_HEADERFILE                  197
#define IDB_SOURCEFILE                  198
#define IDR_ESBSERVER_POPUPMENU         200
#define IDI_ESBSERVER_MANAGER           201
#define IDI_WORKSPACE                   202
#define IDR_WORKSPACE_POPUPMENU         203
#define IDB_WORKSPACE                   204
#define IDI_TYPEBROWSER                 205
#define IDD_SCOPEDNAME_BROWSER          206
#define IDD_OULINE_BROWSER_PROPERTY_PANEL 207
#define IDD_OULINE_BROWSER_PROPERTIES_PANEL 207
#define IDD_OUTLINE_BROWSER_PROPERTIES_PANEL 207
#define IDB_TYPE_HIERARCHY_F            209
#define IDB_SUBTYPE_HIERARCHY_F         210
#define IDB_LOCK_HIERARCHY_F            211
#define IDB_INHERITED_MEMBERS_F         212
#define IDB_LOCK_HIERARCHY_A            213
#define IDD_HIERARCHY_BROWSER_PANEL     213
#define IDB_INHERITED_MEMBERS_A         214
#define IDI_HIERARCHY_BROWSER           214
#define IDI_HIERARCHY                   214
#define IDB_SUBTYPE_HIERARCHY_A         215
#define IDD_DIALOG1                     215
#define IDD_PACKAGE_BROWSER_PANEL       215
#define IDB_TYPE_HIERARCHY_A            216
#define IDB_SUPERTYPE_HIERARCHY_A       217
#define IDB_SUPERTYPE_HIERARCHY_F       218
#define IDB_PUBLIC_METHOD               219
#define IDB_PROTECTED_METHOD            220
#define IDB_PRIVATE_METHOD              221
#define IDI_PACKAGE_BROWSER             222
#define IDB_VARIABLE                    222
#define IDB_PACKAGES_A                  223
#define IDB_MEMBERS_A                   224
#define IDB_TYPES_A                     225
#define IDR_PREVIOUS_HIERARCHIES_POPUPMENU 227
#define IDB_QUESTIONMARK                228
#define IDB_PROBLEM                     229
#define IDB_PREVIOUS_HIERARCHIES_A      230
#define IDB_PREVIOUS_HIERARCHIES_F      231
#define IDB_SELECTION_ARROW             232
#define IDR_HIERARCHY_BROWSER_POPUPMENU 233
#define IDB_PROTOTYPE                   233
#define IDD_APPEARANCE_PROPERTIES_PANEL 235
#define IDD_HIERARCHY_BROWSER_PROPERTIES_PANEL 236
#define IDD_LOGGER_PANEL                237
#define IDI_LOG_WINDOW                  238
#define IDD_VERSION_CHECKING            239
#define IDI_FILTER                      239
#define IDD_LOGGER_PROPERTIES_PANEL     240
#define IDD_PROGRESS                    243
#define IDR_CUSTOM_OUTLINE_FILTER       245
#define IDD_CUSTOM_OUTLINE_FILTER       246
#define IDB_FILTER_A                    247
#define IDB_FILTER_F                    248
#define IDC_FILE_INFO                   1002
#define IDC_TYPE_BROWSER                1002
#define IDC_TOPLEFT1                    1004
#define IDC_TOPLEFT                     1004
#define IDC_TOPRIGHT1                   1005
#define IDC_TOPRIGHT                    1005
#define IDC_OUTLINE_BROWSER             1005
#define IDC_BOTTOMLEFT1                 1006
#define IDC_HIERARCHY_BROWSER           1006
#define IDC_BOTTOMLEFT                  1006
#define IDC_BOTTOMRIGHT1                1007
#define IDC_BOTTOMRIGHT                 1007
#define IDC_OUTLINE                     1008
#define IDC_CLOSE                       1009
#define IDC_CLOSER                      1009
#define IDC_ONLY_PUBLIC                 1010
#define IDC_NO_STATIC                   1011
#define IDC_SORT                        1013
#define IDC_BUTTON1                     1015
#define IDC_CHECK1                      1016
#define IDC_SHOW_RETURN_TYPES           1016
#define IDC_WARN_MULTIPLE_PARENTS       1016
#define IDC_DISABLE                     1016
#define IDC_SHOW_CTAGGER                1016
#define IDC_TYPE_CLASS                  1016
#define IDC_OUTLINE_PUBLIC_ONLY         1017
#define IDC_MOUSE_POS                   1017
#define IDC_OUTLINE_NO_STATIC           1018
#define IDC_CTAGGER                     1018
#define IDC_OUTLINE_NO_FIELDS           1019
#define IDC_WORKSPACE                   1019
#define IDC_OUTLINE_SORT                1020
#define IDC_FILEFILTER                  1021
#define IDC_CHOOSE                      1022
#define IDC_QUALIFIER_LABEL             1023
#define IDC_METHOD_BROWSER              1025
#define IDC_PREFERENCES                 1026
#define IDC_EDIT1                       1027
#define IDC_CTAGS_EXE                   1027
#define IDC_HOVER                       1027
#define IDC_ROLL_TIME                   1027
#define IDC_RADIO2                      1028
#define IDC_RADIO3                      1029
#define IDC_RADIO4                      1030
#define IDC_BUTTON3                     1032
#define IDC_EDIT2                       1033
#define IDC_ADDITIONAL_CTAGS_OPTIONS    1033
#define IDC_ROLL_SIZE                   1033
#define IDC_ROLL_WIDTH                  1033
#define IDC_FIELDS                      1033
#define IDC_SHOW_HEADER_AND_SOURCE_FILE_CONETENT 1035
#define IDC_TREE1                       1036
#define IDC_HIERARCHY                   1036
#define IDC_LIST1                       1037
#define IDC_MEMBERS                     1037
#define IDC_CLASSES                     1037
#define IDC_LOG_ENTRY_LIST              1037
#define IDC_TYPE_HIERARCHY              1038
#define IDC_SUBTYPE_HIERARCHY           1039
#define IDC_NAMESPACES                  1039
#define IDC_SUPERTYPE_HIERARCHY         1040
#define IDC_MEMBERS1                    1040
#define IDC_LOCK_HIERARCHY              1041
#define IDC_PACKAGES_BROWSER            1041
#define IDC_INHERITED_MEMBERS           1042
#define IDC_SPLITTERBAR1                1042
#define IDC_SPLITTERBAR2                1044
#define IDC_NSPACE_CAPTION              1045
#define IDC_GRBOX                       1046
#define IDC_MEMBERS_CAPTION             1047
#define IDC_SHOW_NAMESPACES             1047
#define IDC_TYPES_CAPTION               1048
#define IDC_SPLITTER                    1048
#define IDC_OUTLINE_LABEL               1051
#define IDC_OUTLINE_ICON                1052
#define IDC_CLOSE_ON_RETURN             1053
#define IDC_SERVER_NAME                 1055
#define IDC_AUTO_RAISE                  1056
#define IDC_HIDE                        1057
#define IDC_BUTTON2                     1058
#define IDC_BROWSE                      1060
#define IDC_SHOW_TOOLTIPS               1061
#define IDC_HOMEPAGE                    1062
#define IDC_THIS_VERSION                1063
#define IDC_LATEST_VERSION              1064
#define IDC_DOWNLOADPAGE                1065
#define IDC_MATCHES                     1066
#define IDC_FULLSCREEN                  1067
#define IDC_ROLL                        1067
#define IDC_SPACER                      1069
#define IDC_ALLWAYS_ONTOP               1070
#define IDC_FADE                        1071
#define IDC_MIN_OPACITY                 1072
#define IDC_MAX_OPACITY                 1073
#define IDC_FADE_TIME                   1074
#define IDC_EDIT3                       1075
#define IDC_ROLL_HEIGHT                 1075
#define IDC_METHODS                     1075
#define IDC_ENLARGE                     1077
#define IDC_PROGRESS                    1078
#define IDC_PREFIX                      1081
#define IDC_POSTFIX                     1082
#define IDC_LINK                        1083
#define IDC_LOGLEVEL                    1084
#define IDC_CHECK2                      1086
#define IDC_TYPE_STRUCT                 1086
#define IDC_CHECK3                      1087
#define IDC_TYPE_UNION                  1087
#define IDC_CHECK4                      1088
#define IDC_TYPE_TYPEDEF                1088
#define IDC_CHECK5                      1089
#define IDC_TYPE_ENUM                   1089
#define IDC_CHECK6                      1090
#define IDC_FIELD_PUBLIC                1090
#define IDC_CHECK7                      1091
#define IDC_FIELD_PRIVATE               1091
#define IDC_CHECK8                      1092
#define IDC_FIELD_PROTECTED             1092
#define IDC_CHECK9                      1093
#define IDC_FIELD_CONST                 1093
#define IDC_CHECK10                     1094
#define IDC_FIELD_STATIC                1094
#define IDC_CHECK11                     1095
#define IDC_METHOD_PUBLIC               1095
#define IDC_CHECK12                     1096
#define IDC_METHOD_PRIVATE              1096
#define IDC_CHECK13                     1097
#define IDC_METHOD_PROTECTED            1097
#define IDC_CHECK14                     1098
#define IDC_METHOD_CONST                1098
#define IDC_CHECK15                     1099
#define IDC_METHOD_STATIC               1099
#define IDC_CHECK16                     1100
#define IDC_METHOD_ABSTRACT             1100
#define IDC_CHECK17                     1101
#define IDC_METHOD_VIRTUAL              1101
#define IDC_CHECK18                     1102
#define IDC_TYPE_PUBLIC                 1102
#define IDC_CHECK19                     1103
#define IDC_TYPE_PRIVATE                1103
#define IDC_CHECK20                     1104
#define IDC_TYPE_PROTECTED              1104
#define IDC_QUALIFIERS                  4000
#define IDD_TYPE_BROWSER                4000
#define IDC_TYPES                       4001
#define IDC_FILTER                      4002
#define IDC_TYPEFILTER                  4002
#define ID_OUTLINEBROWSER_HEADER        32773
#define ID_OUTLINEBROWSER_SOURCE        32774
#define ID_ESBSERVER_EXIT               32775
#define ID_ESBSERVER_MAXIMIZE           32776
#define ID_ESBSERVER_TYPEBROWSER        32777
#define ID_ESBSERVER_REPARSE            32778
#define ID_ESBSERVER_MINIMIZE           32779
#define ID_OUTLINEBROWSER_INSPECT       32780
#define ID_REPARSE_OUTLINE              32781
#define ID_ESBSERVER_WORKSPACEBROWSER   32782
#define ID_ESBSERVER_ESBSERVER          32783
#define ID_ESBSERVER_METHODBROWSER      32784
#define ID_ESBSERVER_PREFERENCES        32785
#define ID_OUTLINEBROWSER_HIERARCHY     32786
#define IDC_PREVIOUS_HIERARCHIES        32787
#define ID_PREVIOUSHIERARCHIES          32793
#define ID_HIERARCHY_FOCUSON            32794
#define ID_HIERARCHY_FOCUSONX           32796
#define ID_ESBSERVER_ABOUT              32797
#define ID_ESBSERVER_LOGWINDOW          32798

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        248
#define _APS_NEXT_COMMAND_VALUE         32799
#define _APS_NEXT_CONTROL_VALUE         1102
#define _APS_NEXT_SYMED_VALUE           108
#endif
#endif
